services:
  - type: web
    name: dou-bot
    env: python
    plan: free
    region: frankfurt
    runtime: "python-3.11"
    buildCommand: "pip install -r requirements.txt"
    startCommand: "python main.py"
